[package]
name = "poker_calc"
version = "0.1.0"
authors = ["Paul Hunter <phunter510@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rs_poker = "1.0.0"
